# NOTE: This file is auto generated by OpenAPI Generator 7.15.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SDKAPI.Model.ErrorInternalServerError do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :error
  ]

  @type t :: %__MODULE__{
    :error => SDKAPI.Model.ErrorError.t
  }

  alias SDKAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:error, :struct, SDKAPI.Model.ErrorError)
  end
end

