# NOTE: This file is auto generated by OpenAPI Generator 7.16.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SDKAPI.Model.EvaluateResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :feature_key,
    :enabled,
    :value
  ]

  @type t :: %__MODULE__{
    :feature_key => String.t,
    :enabled => boolean(),
    :value => String.t
  }

  def decode(value) do
    value
  end
end

