# NOTE: This file is auto generated by OpenAPI Generator 7.15.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SDKAPI.Model.FeatureErrorReport do
  @moduledoc """

  """

  @derive JSON.Encoder
  defstruct [
    :error_type,
    :error_message,
    :context
  ]

  @type t :: %__MODULE__{
    :error_type => String.t,
    :error_message => String.t,
    :context => %{optional(String.t) => any()} | nil
  }

  alias SDKAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:context, :map, SDKAPI.Model.AnyType)
  end
end
