# NOTE: This file is auto generated by OpenAPI Generator 7.15.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SDKAPI.Model.FeatureHealth do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :feature_key,
    :environment_key,
    :enabled,
    :auto_disabled,
    :error_rate,
    :threshold,
    :last_error_at
  ]

  @type t :: %__MODULE__{
    :feature_key => String.t,
    :environment_key => String.t,
    :enabled => boolean(),
    :auto_disabled => boolean(),
    :error_rate => float() | nil,
    :threshold => float() | nil,
    :last_error_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

