# NOTE: This file is auto generated by OpenAPI Generator 7.15.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SDKAPI.Model.HealthResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :status,
    :server_time
  ]

  @type t :: %__MODULE__{
    :status => String.t,
    :server_time => DateTime.t
  }

  def decode(value) do
    value
  end
end

