# NOTE: This file is auto generated by OpenAPI Generator 7.16.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule SDKAPI.Model.TrackRequest do
  @moduledoc """
  Event sent from SDK. SDK SHOULD send an impression event for each evaluation (recommended). Conversions / errors / custom events are used to update algorithm statistics. 
  """

  @derive JSON.Encoder
  defstruct [
    :variant_key,
    :event_type,
    :reward,
    :context,
    :created_at,
    :dedup_key
  ]

  @type t :: %__MODULE__{
    :variant_key => String.t,
    :event_type => String.t,
    :reward => float() | nil,
    :context => %{optional(String.t) => any()} | nil,
    :created_at => DateTime.t | nil,
    :dedup_key => String.t | nil
  }

  alias SDKAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:context, :map, SDKAPI.Model.AnyType)
  end
end

